### ISSUE TITLE
Admin 계정 생성을 한다.

### ISSUE THREAD

**Issue by KwonJuHwan** [fcstudy-project/FastTime-backend#10]
# 목적
## Admin 계정 생성을 어떻게 처리할 것인지
Admin 페이지를 Spring으로 구현해본 적이 없어, Admin 계정을 생성할 때, 어떤 식으로 생성하면 좋을지 의견을 묻고자 이슈를 올렸습니다.

### 1. 회원 가입으로 Admin 계정 생성
회원 가입을 할 때, Admin 계정을 생성할 수 있는 이메일을 미리 지정 해놓고, 사용자가 해당 이메일로 접근 시, Admin 계정으로 회원 가입이 가능하도록 설정

### 2. DB에 직접 접근하여 Admin 계정 생성
말 그대로 Admin Entity를 DB에 직접 넣어서 생성

### _제가 생각한 케이스는 이 정도인데, 많은 의견 부탁드립니다😊_
<br>
<br>

# 개발내용
- [x] Admin 계정 생성 코드 구현

<br>
<br>

**Comment by ghrltjdtprbs** [comment]
**1. 회원 가입으로 Admin 계정 생성**
이 경우 한 개의 Admin계정을 만들기 위해 admin회원가입 로직을 새로 짜야 하는데,
저는 개인적으로 비효율적이라고 생각합니다.
또한 이 경우 두 가지 문제점이 걱정됩니다.
- admin 회원가입 로직을 그대로 코드에 업로드할 경우 :  관리자가 아닌 다른 사용자도 로직을 볼 수 있음
- admin 회원가입 로직을 삭제하고 하고 업로드할 경우 : 후에 admin계정을 추가생성 할 경우가 생기면 코드 관리가 어려움

**2. DB에 직접 접근하여 Admin계정 생성**
이 경우에도 Spring Security를 이용할 경우 해싱되지 않은 비밀번호가 데이터베이스에 저장되어 보안문제가 발생합니다.

이 부분은 현업에서 어떻게 적용되고 있는지 멘토님 의견을 들어봐도 좋을 것 같습니다!

**Comment by JeongUijeong** [comment]
전 1번 케이스가 더 좋을 것 같습니다! 
직접 DB에 접근해 계정을 생성하는 경우는 앞서 혜미님이 남겨주신 코멘트처럼 비밀번호 해싱 문제가 우려되기 때문인데요. 
다만, 1번 케이스로 진행할 때 관리자 용 이메일을 어떻게 지정해둘 것인 지에 대해 회의가 필요할 것 같네요!
다른 방안이 있을 지 금일 회의 전까지 더 생각해보겠습니다. 🙂
