### ISSUE TITLE
WebConfig 보안 재설정이 필요해보입니다.

### ISSUE THREAD

**Issue by Nine-JH** [fcstudy-project/FastTime-backend#42]
# 목적
## 1. `InterceptorRegistration.addPathPatterns()` 경로 오류
```java
public void addInterceptors(InterceptorRegistry registry) {
    registry.addInterceptor(new AdminCheckInterceptor())
        .order(1)
        .addPathPatterns("/v1/admin");
     registry.addInterceptor(new LoginCheckInterceptor())
        .order(2)
        .addPathPatterns("/api/v1/post", "/api/v1/comment",
            "v1/retouch-member", "v1/logout", "v1/delete");
    }
```
* 현재 경로는 `/v1/admin`, `/api/v1/post` 등으로 되어있습니다. 하지만 이는 정확하게 일치하는 경로만 인터셉터에 적용되기 때문에 Comment API 들인 `/api/v1/comment/create` 등은 적용되지 않을 수 있습니다. 이에 따른 변경안이 필요해보입니다.

* 추가적으로 하위 경로 전체 적용인 `/**` 패턴을 적용하게 되면, 조회 역시 안되는 위험성이 있기 때문에 주의해서 적용해야 할 것 같습니다.

<br>
<br>

## 2. 테스트 코드에 인터셉터 침투 (테스트 환경 독립성이 보장이 안됨)
현재 FastTime의 `ControllerUnitTest`의 주 목적은 다음과 같습니다.
* 입력값 검증이고 
* 일관적인 포맷(ResponseDto)으로 반환 하는가?
 
<br>

로그인과 같은 인증의 경우에는 **Presentation layer 의 unit test 보다는, intergration test에 포함되는 것이 더욱 적절**해보이기 때문에, 인증 인터셉터 적용을 제외할 필요성이 있어 보입니다. 

<br>
<br>

# 제안
필터로 구현되어있다면 간단히 `@WebMvcTest`의 excludeFilter property로 설정이 가능하지만 인터셉터로 구현되어 있기 떄문에 다른 방식이 필요합니다.

<br>
<br>

## profile에 따라 interceptor 적용
`@Profile`을 통해 profile name 별로 Bean 등록을 할 수 있습니다.
```java
@Profile({"local", "prod"})
@Configuration
public class WebConfig implements WebMvcConfigurer {

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(new AdminCheckInterceptor())
            .order(1)
            .addPathPatterns("/v1/admin");
        registry.addInterceptor(new LoginCheckInterceptor())
            .order(2)
            .addPathPatterns("/api/v1/post", "/api/v1/comment",
                "v1/retouch-member", "v1/logout", "v1/delete");
    }
}
``` 

이후 test 에서 profile 을 두 profile 이외의 것들로 설정을 하면 됩니다.
```yaml
spring:
  profiles:
    include: test
```
기본적으로 메인 로직에서 Profile 설정을 꼭 해주어야 하기 때문에 설정이 번거로울 수는 있습니다.

**Comment by KwonJuHwan** [comment]
내일 메소드 소문자로 리팩토링이랑 같이 작업해서 수정해서 내일 올리겠습니다
