### ISSUE TITLE
Backend CORS 수정하기

### ISSUE THREAD

**Issue by Nine-JH** [fcstudy-project/FastTime-backend#51]
프론트엔드측에서 CORS 문제를 겪고 있습니다.
아마 현재 로컬로 개발중일테니 전체 개방으로 CORS 허용을 하되 후에 프론트엔드 IP만 허용해주시면 될 것 같습니다.

**Comment by KwonJuHwan** [comment]
처리 완료 된 부분 아닌가요??

**Comment by Nine-JH** [comment]
일단 기록으로 남기기위해서 작성했습니다 PR에 issue 연결하시고 close 하시면 됩니다.
