### ISSUE TITLE
Login Interceptor 수정

### ISSUE THREAD

**Issue by Nine-JH** [fcstudy-project/FastTime-backend#53]
현재 Login Inteceptor은 로그인이 되어있지 않다면 `/api/v1/login`으로 redirect 하는 로직을 수행합니다.
```java
@Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response,
        Object handler) throws Exception {
        String requestURI = request.getRequestURI();
        HttpSession session = request.getSession(false);

        if (session == null || (session.getAttribute("MEMBER") == null
            && session.getAttribute("ADMIN") == null)) {
            response.sendRedirect("/api/v1/login");
            log.info("접근 거부");
            return false;

        }
        return true;
    }
```

* 백엔드에서 `thymeleaf`를 사용해 view 까지 만들던때에는 리다이렉트가 맞지만, 이제는 프론트엔드가 그를 담당하기 때문에 다른 방법이 필요해보입니다.
* 한가지 방법으로는 로그인이 되어있지 않는다는 시그널을 프론트엔드에게 보내는 식이 있습니다. (ex: 401, 403 ERROR)
  * 예시 뿐이니 좋은 방법이 있다면 얼마든지 채택하셔도 좋습니다. 

### 참고 자료
[MDN Http Status Reference](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwig8_ir1-qBAxURf94KHbuYDLEQFnoECAsQAQ&url=https%3A%2F%2Fdeveloper.mozilla.org%2Fko%2Fdocs%2FWeb%2FHTTP%2FStatus&usg=AOvVaw3ssd-w2AJkTM_UhUXAwJT1&opi=89978449)

**Comment by KwonJuHwan** [comment]
403 포비든으로 하는 것이 적절해보이겠네요 수정하겠습니다
