### ISSUE TITLE
회원 정보 조회 API

### ISSUE THREAD

**Issue by Nine-JH** [fcstudy-project/FastTime-backend#54]
마이페이지에서 회원 정보를 조회하기 위한 API가 누락되어있습니다.
프론트엔드분과 협의를 해 적절한 필드를 DTO로 wrapping하여 제공해주면 좋을 것 같습니다.

**Comment by ghrltjdtprbs** [comment]
MemberController에 로그인된 사용자의 닉네임, 프로필사진url, 이메일 정보를 받아오는 로직 구현 완료
