### ISSUE TITLE
회원 비밀번호 암호화 누락

### ISSUE THREAD

**Issue by Nine-JH** [fcstudy-project/FastTime-backend#55]
회원가입 시 비밀번호 암호화를 수행하는 로직이 누락되어있습니다.
법적으로도 명시가 되어있는만큼 꼭 구현을 해주시기 바랍니다.

**Comment by ghrltjdtprbs** [comment]
pr보낼 때 비밀번호 암호화 하는 코드를 주석처리해서 보냈었는데 누락이 되었나요? 다시 한번 확인하겠습니다!
